version: '3.8'

services:
  qubit-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qubit-frontend
    ports:
      - "5498:80"
    restart: unless-stopped
    # For development with hot-reload, uncomment these lines:
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    # command: npm start
